"""
常量模块 - 包含表情映射、AI提示词等
"""

from .emotions import (
    VALID_EMOTIONS,
    AUDIO_EMOTION_MAP,
    EMOTION_DISPLAY_NAMES,
)
from .prompts import (
    SYSTEM_PROMPT,
    EMOTION_SELECTOR_PROMPT,
    TEXT_GENERATION_PROMPT,
    JAPANESE_TRANSLATION_PROMPT,
    BILINGUAL_GENERATION_PROMPT,
    PRESET_SELECTOR_PROMPT,
)
from .voice_responses import (
    VOICE_RESPONSES,
    PRESET_TEXT_MAP,
)

__all__ = [
    'VALID_EMOTIONS',
    'AUDIO_EMOTION_MAP',
    'EMOTION_DISPLAY_NAMES',
    'SYSTEM_PROMPT',
    'EMOTION_SELECTOR_PROMPT',
    'TEXT_GENERATION_PROMPT',
    'JAPANESE_TRANSLATION_PROMPT',
    'BILINGUAL_GENERATION_PROMPT',
    'PRESET_SELECTOR_PROMPT',
    'VOICE_RESPONSES',
    'PRESET_TEXT_MAP',
]
